### ISSUE TITLE
[Bug] Element in the UI can be marked/selected by the cursor

### ISSUE THREAD

**Issue by MichaMican** [glueckkanja/MyWorkID#95]
### Check for duplicate issues

- [x] I have verified that this issue has not been reported before

### Describe the bug

All elements in the UI can be selected with the cursor..
Expected:
The following elements definately should not be selectable/copieable:
- Logo
- Icons
- Profile picture of the user
- Name of the Actions on the blue buttons

### Affected version

v2025.3.1

### How can we reproduce the issue?

1. Open MyWorkID
2. Move mouse cursor to the right of the `glueckkanja` logo
3. leftclick and hold to "select the whole page"
4. See result (Screenshot)

### Screenshots

![Image](https://github.com/user-attachments/assets/c434d997-4d03-4146-9b95-dc8782f62784)

### Console output (frontend)

```shell
N/A
```

### Log output (backend)

```shell
N/A
```

### Additional context

Simplest solution would be to use the css `user-select` properties of as many browsers as possible:
```css
.no-select {
        user-select: none;
        -moz-user-select: none;
        -khtml-user-select: none;
        -webkit-user-select: none;
        -o-user-select: none;
}
```
